// Все страны мира — ISO 3166-1 alpha-2, названия RU/EN, emoji флаг
export const COUNTRIES = [
  { code: 'AF', nameRu: 'Афганистан', nameEn: 'Afghanistan', flag: '🇦🇫' },
  { code: 'AL', nameRu: 'Албания', nameEn: 'Albania', flag: '🇦🇱' },
  { code: 'DZ', nameRu: 'Алжир', nameEn: 'Algeria', flag: '🇩🇿' },
  { code: 'AD', nameRu: 'Андорра', nameEn: 'Andorra', flag: '🇦🇩' },
  { code: 'AO', nameRu: 'Ангола', nameEn: 'Angola', flag: '🇦🇴' },
  { code: 'AG', nameRu: 'Антигуа и Барбуда', nameEn: 'Antigua and Barbuda', flag: '🇦🇬' },
  { code: 'AR', nameRu: 'Аргентина', nameEn: 'Argentina', flag: '🇦🇷' },
  { code: 'AM', nameRu: 'Армения', nameEn: 'Armenia', flag: '🇦🇲' },
  { code: 'AU', nameRu: 'Австралия', nameEn: 'Australia', flag: '🇦🇺' },
  { code: 'AT', nameRu: 'Австрия', nameEn: 'Austria', flag: '🇦🇹' },
  { code: 'AZ', nameRu: 'Азербайджан', nameEn: 'Azerbaijan', flag: '🇦🇿' },
  { code: 'BS', nameRu: 'Багамские Острова', nameEn: 'Bahamas', flag: '🇧🇸' },
  { code: 'BH', nameRu: 'Бахрейн', nameEn: 'Bahrain', flag: '🇧🇭' },
  { code: 'BD', nameRu: 'Бангладеш', nameEn: 'Bangladesh', flag: '🇧🇩' },
  { code: 'BB', nameRu: 'Барбадос', nameEn: 'Barbados', flag: '🇧🇧' },
  { code: 'BY', nameRu: 'Белоруссия', nameEn: 'Belarus', flag: '🇧🇾' },
  { code: 'BE', nameRu: 'Бельгия', nameEn: 'Belgium', flag: '🇧🇪' },
  { code: 'BZ', nameRu: 'Белиз', nameEn: 'Belize', flag: '🇧🇿' },
  { code: 'BJ', nameRu: 'Бенин', nameEn: 'Benin', flag: '🇧🇯' },
  { code: 'BT', nameRu: 'Бутан', nameEn: 'Bhutan', flag: '🇧🇹' },
  { code: 'BO', nameRu: 'Боливия', nameEn: 'Bolivia', flag: '🇧🇴' },
  { code: 'BA', nameRu: 'Босния и Герцеговина', nameEn: 'Bosnia and Herzegovina', flag: '🇧🇦' },
  { code: 'BW', nameRu: 'Ботсвана', nameEn: 'Botswana', flag: '🇧🇼' },
  { code: 'BR', nameRu: 'Бразилия', nameEn: 'Brazil', flag: '🇧🇷' },
  { code: 'BN', nameRu: 'Бруней', nameEn: 'Brunei', flag: '🇧🇳' },
  { code: 'BG', nameRu: 'Болгария', nameEn: 'Bulgaria', flag: '🇧🇬' },
  { code: 'BF', nameRu: 'Буркина-Фасо', nameEn: 'Burkina Faso', flag: '🇧🇫' },
  { code: 'BI', nameRu: 'Бурунди', nameEn: 'Burundi', flag: '🇧🇮' },
  { code: 'CV', nameRu: 'Кабо-Верде', nameEn: 'Cabo Verde', flag: '🇨🇻' },
  { code: 'KH', nameRu: 'Камбоджа', nameEn: 'Cambodia', flag: '🇰🇭' },
  { code: 'CM', nameRu: 'Камерун', nameEn: 'Cameroon', flag: '🇨🇲' },
  { code: 'CA', nameRu: 'Канада', nameEn: 'Canada', flag: '🇨🇦' },
  { code: 'CF', nameRu: 'ЦАР', nameEn: 'Central African Republic', flag: '🇨🇫' },
  { code: 'TD', nameRu: 'Чад', nameEn: 'Chad', flag: '🇹🇩' },
  { code: 'CL', nameRu: 'Чили', nameEn: 'Chile', flag: '🇨🇱' },
  { code: 'CN', nameRu: 'Китай', nameEn: 'China', flag: '🇨🇳' },
  { code: 'CO', nameRu: 'Колумбия', nameEn: 'Colombia', flag: '🇨🇴' },
  { code: 'KM', nameRu: 'Коморские Острова', nameEn: 'Comoros', flag: '🇰🇲' },
  { code: 'CG', nameRu: 'Республика Конго', nameEn: 'Congo', flag: '🇨🇬' },
  { code: 'CD', nameRu: 'ДР Конго', nameEn: 'DR Congo', flag: '🇨🇩' },
  { code: 'CR', nameRu: 'Коста-Рика', nameEn: 'Costa Rica', flag: '🇨🇷' },
  { code: 'HR', nameRu: 'Хорватия', nameEn: 'Croatia', flag: '🇭🇷' },
  { code: 'CU', nameRu: 'Куба', nameEn: 'Cuba', flag: '🇨🇺' },
  { code: 'CY', nameRu: 'Кипр', nameEn: 'Cyprus', flag: '🇨🇾' },
  { code: 'CZ', nameRu: 'Чехия', nameEn: 'Czechia', flag: '🇨🇿' },
  { code: 'DK', nameRu: 'Дания', nameEn: 'Denmark', flag: '🇩🇰' },
  { code: 'DJ', nameRu: 'Джибути', nameEn: 'Djibouti', flag: '🇩🇯' },
  { code: 'DM', nameRu: 'Доминика', nameEn: 'Dominica', flag: '🇩🇲' },
  { code: 'DO', nameRu: 'Доминиканская Республика', nameEn: 'Dominican Republic', flag: '🇩🇴' },
  { code: 'EC', nameRu: 'Эквадор', nameEn: 'Ecuador', flag: '🇪🇨' },
  { code: 'EG', nameRu: 'Египет', nameEn: 'Egypt', flag: '🇪🇬' },
  { code: 'SV', nameRu: 'Сальвадор', nameEn: 'El Salvador', flag: '🇸🇻' },
  { code: 'GQ', nameRu: 'Экваториальная Гвинея', nameEn: 'Equatorial Guinea', flag: '🇬🇶' },
  { code: 'ER', nameRu: 'Эритрея', nameEn: 'Eritrea', flag: '🇪🇷' },
  { code: 'EE', nameRu: 'Эстония', nameEn: 'Estonia', flag: '🇪🇪' },
  { code: 'SZ', nameRu: 'Эсватини', nameEn: 'Eswatini', flag: '🇸🇿' },
  { code: 'ET', nameRu: 'Эфиопия', nameEn: 'Ethiopia', flag: '🇪🇹' },
  { code: 'FJ', nameRu: 'Фиджи', nameEn: 'Fiji', flag: '🇫🇯' },
  { code: 'FI', nameRu: 'Финляндия', nameEn: 'Finland', flag: '🇫🇮' },
  { code: 'FR', nameRu: 'Франция', nameEn: 'France', flag: '🇫🇷' },
  { code: 'GA', nameRu: 'Габон', nameEn: 'Gabon', flag: '🇬🇦' },
  { code: 'GM', nameRu: 'Гамбия', nameEn: 'Gambia', flag: '🇬🇲' },
  { code: 'GE', nameRu: 'Грузия', nameEn: 'Georgia', flag: '🇬🇪' },
  { code: 'DE', nameRu: 'Германия', nameEn: 'Germany', flag: '🇩🇪' },
  { code: 'GH', nameRu: 'Гана', nameEn: 'Ghana', flag: '🇬🇭' },
  { code: 'GR', nameRu: 'Греция', nameEn: 'Greece', flag: '🇬🇷' },
  { code: 'GD', nameRu: 'Гренада', nameEn: 'Grenada', flag: '🇬🇩' },
  { code: 'GT', nameRu: 'Гватемала', nameEn: 'Guatemala', flag: '🇬🇹' },
  { code: 'GN', nameRu: 'Гвинея', nameEn: 'Guinea', flag: '🇬🇳' },
  { code: 'GW', nameRu: 'Гвинея-Бисау', nameEn: 'Guinea-Bissau', flag: '🇬🇼' },
  { code: 'GY', nameRu: 'Гайана', nameEn: 'Guyana', flag: '🇬🇾' },
  { code: 'HT', nameRu: 'Гаити', nameEn: 'Haiti', flag: '🇭🇹' },
  { code: 'HN', nameRu: 'Гондурас', nameEn: 'Honduras', flag: '🇭🇳' },
  { code: 'HU', nameRu: 'Венгрия', nameEn: 'Hungary', flag: '🇭🇺' },
  { code: 'IS', nameRu: 'Исландия', nameEn: 'Iceland', flag: '🇮🇸' },
  { code: 'IN', nameRu: 'Индия', nameEn: 'India', flag: '🇮🇳' },
  { code: 'ID', nameRu: 'Индонезия', nameEn: 'Indonesia', flag: '🇮🇩' },
  { code: 'IR', nameRu: 'Иран', nameEn: 'Iran', flag: '🇮🇷' },
  { code: 'IQ', nameRu: 'Ирак', nameEn: 'Iraq', flag: '🇮🇶' },
  { code: 'IE', nameRu: 'Ирландия', nameEn: 'Ireland', flag: '🇮🇪' },
  { code: 'IL', nameRu: 'Израиль', nameEn: 'Israel', flag: '🇮🇱' },
  { code: 'IT', nameRu: 'Италия', nameEn: 'Italy', flag: '🇮🇹' },
  { code: 'JM', nameRu: 'Ямайка', nameEn: 'Jamaica', flag: '🇯🇲' },
  { code: 'JP', nameRu: 'Япония', nameEn: 'Japan', flag: '🇯🇵' },
  { code: 'JO', nameRu: 'Иордания', nameEn: 'Jordan', flag: '🇯🇴' },
  { code: 'KZ', nameRu: 'Казахстан', nameEn: 'Kazakhstan', flag: '🇰🇿' },
  { code: 'KE', nameRu: 'Кения', nameEn: 'Kenya', flag: '🇰🇪' },
  { code: 'KI', nameRu: 'Кирибати', nameEn: 'Kiribati', flag: '🇰🇮' },
  { code: 'KP', nameRu: 'КНДР', nameEn: 'North Korea', flag: '🇰🇵' },
  { code: 'KR', nameRu: 'Южная Корея', nameEn: 'South Korea', flag: '🇰🇷' },
  { code: 'KW', nameRu: 'Кувейт', nameEn: 'Kuwait', flag: '🇰🇼' },
  { code: 'KG', nameRu: 'Киргизия', nameEn: 'Kyrgyzstan', flag: '🇰🇬' },
  { code: 'LA', nameRu: 'Лаос', nameEn: 'Laos', flag: '🇱🇦' },
  { code: 'LV', nameRu: 'Латвия', nameEn: 'Latvia', flag: '🇱🇻' },
  { code: 'LB', nameRu: 'Ливан', nameEn: 'Lebanon', flag: '🇱🇧' },
  { code: 'LS', nameRu: 'Лесото', nameEn: 'Lesotho', flag: '🇱🇸' },
  { code: 'LR', nameRu: 'Либерия', nameEn: 'Liberia', flag: '🇱🇷' },
  { code: 'LY', nameRu: 'Ливия', nameEn: 'Libya', flag: '🇱🇾' },
  { code: 'LI', nameRu: 'Лихтенштейн', nameEn: 'Liechtenstein', flag: '🇱🇮' },
  { code: 'LT', nameRu: 'Литва', nameEn: 'Lithuania', flag: '🇱🇹' },
  { code: 'LU', nameRu: 'Люксембург', nameEn: 'Luxembourg', flag: '🇱🇺' },
  { code: 'MG', nameRu: 'Мадагаскар', nameEn: 'Madagascar', flag: '🇲🇬' },
  { code: 'MW', nameRu: 'Малави', nameEn: 'Malawi', flag: '🇲🇼' },
  { code: 'MY', nameRu: 'Малайзия', nameEn: 'Malaysia', flag: '🇲🇾' },
  { code: 'MV', nameRu: 'Мальдивы', nameEn: 'Maldives', flag: '🇲🇻' },
  { code: 'ML', nameRu: 'Мали', nameEn: 'Mali', flag: '🇲🇱' },
  { code: 'MT', nameRu: 'Мальта', nameEn: 'Malta', flag: '🇲🇹' },
  { code: 'MH', nameRu: 'Маршалловы Острова', nameEn: 'Marshall Islands', flag: '🇲🇭' },
  { code: 'MR', nameRu: 'Мавритания', nameEn: 'Mauritania', flag: '🇲🇷' },
  { code: 'MU', nameRu: 'Маврикий', nameEn: 'Mauritius', flag: '🇲🇺' },
  { code: 'MX', nameRu: 'Мексика', nameEn: 'Mexico', flag: '🇲🇽' },
  { code: 'FM', nameRu: 'Микронезия', nameEn: 'Micronesia', flag: '🇫🇲' },
  { code: 'MD', nameRu: 'Молдова', nameEn: 'Moldova', flag: '🇲🇩' },
  { code: 'MC', nameRu: 'Монако', nameEn: 'Monaco', flag: '🇲🇨' },
  { code: 'MN', nameRu: 'Монголия', nameEn: 'Mongolia', flag: '🇲🇳' },
  { code: 'ME', nameRu: 'Черногория', nameEn: 'Montenegro', flag: '🇲🇪' },
  { code: 'MA', nameRu: 'Марокко', nameEn: 'Morocco', flag: '🇲🇦' },
  { code: 'MZ', nameRu: 'Мозамбик', nameEn: 'Mozambique', flag: '🇲🇿' },
  { code: 'MM', nameRu: 'Мьянма', nameEn: 'Myanmar', flag: '🇲🇲' },
  { code: 'NA', nameRu: 'Намибия', nameEn: 'Namibia', flag: '🇳🇦' },
  { code: 'NR', nameRu: 'Науру', nameEn: 'Nauru', flag: '🇳🇷' },
  { code: 'NP', nameRu: 'Непал', nameEn: 'Nepal', flag: '🇳🇵' },
  { code: 'NL', nameRu: 'Нидерланды', nameEn: 'Netherlands', flag: '🇳🇱' },
  { code: 'NZ', nameRu: 'Новая Зеландия', nameEn: 'New Zealand', flag: '🇳🇿' },
  { code: 'NI', nameRu: 'Никарагуа', nameEn: 'Nicaragua', flag: '🇳🇮' },
  { code: 'NE', nameRu: 'Нигер', nameEn: 'Niger', flag: '🇳🇪' },
  { code: 'NG', nameRu: 'Нигерия', nameEn: 'Nigeria', flag: '🇳🇬' },
  { code: 'MK', nameRu: 'Северная Македония', nameEn: 'North Macedonia', flag: '🇲🇰' },
  { code: 'NO', nameRu: 'Норвегия', nameEn: 'Norway', flag: '🇳🇴' },
  { code: 'OM', nameRu: 'Оман', nameEn: 'Oman', flag: '🇴🇲' },
  { code: 'PK', nameRu: 'Пакистан', nameEn: 'Pakistan', flag: '🇵🇰' },
  { code: 'PW', nameRu: 'Палау', nameEn: 'Palau', flag: '🇵🇼' },
  { code: 'PA', nameRu: 'Панама', nameEn: 'Panama', flag: '🇵🇦' },
  { code: 'PG', nameRu: 'Папуа — Новая Гвинея', nameEn: 'Papua New Guinea', flag: '🇵🇬' },
  { code: 'PY', nameRu: 'Парагвай', nameEn: 'Paraguay', flag: '🇵🇾' },
  { code: 'PE', nameRu: 'Перу', nameEn: 'Peru', flag: '🇵🇪' },
  { code: 'PH', nameRu: 'Филиппины', nameEn: 'Philippines', flag: '🇵🇭' },
  { code: 'PL', nameRu: 'Польша', nameEn: 'Poland', flag: '🇵🇱' },
  { code: 'PT', nameRu: 'Португалия', nameEn: 'Portugal', flag: '🇵🇹' },
  { code: 'QA', nameRu: 'Катар', nameEn: 'Qatar', flag: '🇶🇦' },
  { code: 'RO', nameRu: 'Румыния', nameEn: 'Romania', flag: '🇷🇴' },
  { code: 'RU', nameRu: 'Россия', nameEn: 'Russia', flag: '🇷🇺' },
  { code: 'RW', nameRu: 'Руанда', nameEn: 'Rwanda', flag: '🇷🇼' },
  { code: 'KN', nameRu: 'Сент-Китс и Невис', nameEn: 'Saint Kitts and Nevis', flag: '🇰🇳' },
  { code: 'LC', nameRu: 'Сент-Люсия', nameEn: 'Saint Lucia', flag: '🇱🇨' },
  { code: 'VC', nameRu: 'Сент-Винсент и Гренадины', nameEn: 'Saint Vincent and the Grenadines', flag: '🇻🇨' },
  { code: 'WS', nameRu: 'Самоа', nameEn: 'Samoa', flag: '🇼🇸' },
  { code: 'SM', nameRu: 'Сан-Марино', nameEn: 'San Marino', flag: '🇸🇲' },
  { code: 'ST', nameRu: 'Сан-Томе и Принсипи', nameEn: 'Sao Tome and Principe', flag: '🇸🇹' },
  { code: 'SA', nameRu: 'Саудовская Аравия', nameEn: 'Saudi Arabia', flag: '🇸🇦' },
  { code: 'SN', nameRu: 'Сенегал', nameEn: 'Senegal', flag: '🇸🇳' },
  { code: 'RS', nameRu: 'Сербия', nameEn: 'Serbia', flag: '🇷🇸' },
  { code: 'SC', nameRu: 'Сейшельские Острова', nameEn: 'Seychelles', flag: '🇸🇨' },
  { code: 'SL', nameRu: 'Сьерра-Леоне', nameEn: 'Sierra Leone', flag: '🇸🇱' },
  { code: 'SG', nameRu: 'Сингапур', nameEn: 'Singapore', flag: '🇸🇬' },
  { code: 'SK', nameRu: 'Словакия', nameEn: 'Slovakia', flag: '🇸🇰' },
  { code: 'SI', nameRu: 'Словения', nameEn: 'Slovenia', flag: '🇸🇮' },
  { code: 'SB', nameRu: 'Соломоновы Острова', nameEn: 'Solomon Islands', flag: '🇸🇧' },
  { code: 'SO', nameRu: 'Сомали', nameEn: 'Somalia', flag: '🇸🇴' },
  { code: 'ZA', nameRu: 'ЮАР', nameEn: 'South Africa', flag: '🇿🇦' },
  { code: 'SS', nameRu: 'Южный Судан', nameEn: 'South Sudan', flag: '🇸🇸' },
  { code: 'ES', nameRu: 'Испания', nameEn: 'Spain', flag: '🇪🇸' },
  { code: 'LK', nameRu: 'Шри-Ланка', nameEn: 'Sri Lanka', flag: '🇱🇰' },
  { code: 'SD', nameRu: 'Судан', nameEn: 'Sudan', flag: '🇸🇩' },
  { code: 'SR', nameRu: 'Суринам', nameEn: 'Suriname', flag: '🇸🇷' },
  { code: 'SE', nameRu: 'Швеция', nameEn: 'Sweden', flag: '🇸🇪' },
  { code: 'CH', nameRu: 'Швейцария', nameEn: 'Switzerland', flag: '🇨🇭' },
  { code: 'SY', nameRu: 'Сирия', nameEn: 'Syria', flag: '🇸🇾' },
  { code: 'TW', nameRu: 'Тайвань', nameEn: 'Taiwan', flag: '🇹🇼' },
  { code: 'TJ', nameRu: 'Таджикистан', nameEn: 'Tajikistan', flag: '🇹🇯' },
  { code: 'TZ', nameRu: 'Танзания', nameEn: 'Tanzania', flag: '🇹🇿' },
  { code: 'TH', nameRu: 'Таиланд', nameEn: 'Thailand', flag: '🇹🇭' },
  { code: 'TL', nameRu: 'Восточный Тимор', nameEn: 'Timor-Leste', flag: '🇹🇱' },
  { code: 'TG', nameRu: 'Того', nameEn: 'Togo', flag: '🇹🇬' },
  { code: 'TO', nameRu: 'Тонга', nameEn: 'Tonga', flag: '🇹🇴' },
  { code: 'TT', nameRu: 'Тринидад и Тобаго', nameEn: 'Trinidad and Tobago', flag: '🇹🇹' },
  { code: 'TN', nameRu: 'Тунис', nameEn: 'Tunisia', flag: '🇹🇳' },
  { code: 'TR', nameRu: 'Турция', nameEn: 'Turkey', flag: '🇹🇷' },
  { code: 'TM', nameRu: 'Туркменистан', nameEn: 'Turkmenistan', flag: '🇹🇲' },
  { code: 'TV', nameRu: 'Тувалу', nameEn: 'Tuvalu', flag: '🇹🇻' },
  { code: 'UG', nameRu: 'Уганда', nameEn: 'Uganda', flag: '🇺🇬' },
  { code: 'UA', nameRu: 'Украина', nameEn: 'Ukraine', flag: '🇺🇦' },
  { code: 'AE', nameRu: 'ОАЭ', nameEn: 'United Arab Emirates', flag: '🇦🇪' },
  { code: 'GB', nameRu: 'Великобритания', nameEn: 'United Kingdom', flag: '🇬🇧' },
  { code: 'US', nameRu: 'США', nameEn: 'United States', flag: '🇺🇸' },
  { code: 'UY', nameRu: 'Уругвай', nameEn: 'Uruguay', flag: '🇺🇾' },
  { code: 'UZ', nameRu: 'Узбекистан', nameEn: 'Uzbekistan', flag: '🇺🇿' },
  { code: 'VU', nameRu: 'Вануату', nameEn: 'Vanuatu', flag: '🇻🇺' },
  { code: 'VE', nameRu: 'Венесуэла', nameEn: 'Venezuela', flag: '🇻🇪' },
  { code: 'VN', nameRu: 'Вьетнам', nameEn: 'Vietnam', flag: '🇻🇳' },
  { code: 'YE', nameRu: 'Йемен', nameEn: 'Yemen', flag: '🇾🇪' },
  { code: 'ZM', nameRu: 'Замбия', nameEn: 'Zambia', flag: '🇿🇲' },
  { code: 'ZW', nameRu: 'Зимбабве', nameEn: 'Zimbabwe', flag: '🇿🇼' },
  { code: 'VA', nameRu: 'Ватикан', nameEn: 'Vatican City', flag: '🇻🇦' },
  { code: 'PS', nameRu: 'Палестина', nameEn: 'Palestine', flag: '🇵🇸' },
  { code: 'KV', nameRu: 'Косово', nameEn: 'Kosovo', flag: '🇽🇰' },
];
