-- v7.1.7: BUG #1 fix — геймплейные типы заданий
DO $$ BEGIN
  ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'DAILY_LOGIN';
  ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'FIRST_GAME';
  ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'WIN_N';
  ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'WIN_BOT_N';
  ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'WIN_STREAK_N';
  ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'PLAY_N';
EXCEPTION WHEN duplicate_object THEN null; END $$;

CREATE INDEX IF NOT EXISTS "tasks_taskType_idx" ON "tasks"("taskType");
